name: Auto Label Issues by Keywords

on:
  issues:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = context.payload.issue.title.toLowerCase();
            const body = context.payload.issue.body ? context.payload.issue.body.toLowerCase() : '';
            const labels = [];

            if (title.includes('bug') || body.includes('bug')) {
              labels.push('bug');
            }
            if (title.includes('documentation') || body.includes('documentation')) {
              labels.push('documentation');
            }
            if (title.includes('duplicate') || body.includes('duplicate')) {
              labels.push('duplicate');
            }
            if (title.includes('enhancement') || body.includes('enhancement')) {
              labels.push('enhancement');
            }
            if (title.includes('good first issue') || body.includes('good first issue')) {
              labels.push('good first issue');
            }
            if (title.includes('help wanted') || body.includes('help wanted')) {
              labels.push('help wanted');
            }
            if (title.includes('question') || body.includes('question')) {
              labels.push('question');
            }
            if (title.includes('ui') || body.includes('ui') || title.includes('ux') || body.includes('ux')) {
              labels.push('UI/UX');
            }

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: labels
              });
            }
